name: admin
description: A new Flutter project.
publish_to: "none" # لا تنشر على pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flame: ^1.16.0
  http: ^1.5.0
  file_picker: ^10.3.3
  intl: ^0.20.2
  path_provider: ^2.0.15
  flutter_pdfview: ^1.2.5
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  provider: ^6.1.2
  fl_chart: ^1.1.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.10
  # path_provider: ^2.1.1
  path: ^1.8.3
  # intl: ^0.18.1
  dio: ^5.3.3
  permission_handler: ^11.1.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"

# هنا القسم الصحيح للـ overrides
dependency_overrides:
  vector_math: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
